title: JAY PLUS
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jesamkim.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: 김제삼(Jesam Kim) # add your name
author-img: jesamkim.jpg # add your photo
about-author:
I am a senior sales consultant at Oracle focusing on Cloud Platform.   
Always hungry to keep learning. # add description
social-twitter: jesamkim # add your Twitter handle
social-facebook: jesamkim # add your Facebook handle
social-github: jesamkim # add your Github handle
social-linkedin: jesam-kim-90393a81 # add your Linkedin handle
social-email: sami0823@gmail.com # add your Email address

# Disqus
discus-identifier: jay-plus # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
