title: JAY PLUS (Oracle Cloud를 다루는 블로그)
description: > # this means to ignore newlines until "baseurl:"
  This blog is to share technical tips of Oracle Cloud.
  I'm Jesam Kim a Senior Solution Engineer at Oracle Korea.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jesamkim.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Jesam Kim # add your name
author-img: jesamkim.jpg # add your photo
about-author: A senior solution engineer at Oracle and focusing on Oracle Cloud & Big Data. # add description
social-twitter: jesamkim # add your Twitter handle
social-facebook: jesamkim # add your Facebook handle
social-github: jesamkim # add your Github handle
social-linkedin: jesam-kim-90393a81 # add your Linkedin handle
social-email: sami0823@gmail.com # add your Email address

# Disqus
discus-identifier: jay-plus # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
